version: '3'
services:
    nordvpn:
      image: bubuntux/nordvpn:v3.9.1
      container_name: nordvpn
      cap_add:
        - NET_ADMIN
      devices:
        - /dev/net/tun
      environment:
        - USER=${VPN_USER}
        - PASS=${VPN_PASS}
        - CONNECT=us -g p2p
        - TECHNOLOGY=NordLynx
    transmission:
      image: linuxserver/transmission
      container_name: transmission
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/transmission:/config
        - ${DATA_BASE_PATH}/transmission/downloads:/downloads
        - ${DATA_BASE_PATH}/transmission/watch:/watch
      network_mode: "service:nordvpn"
    nginx:
      image: nginx:1.13-alpine
      container_name: nginx
      stdin_open: true
      ports:
        - "9091:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - nordvpn:transmission
    plex:
      image: linuxserver/plex
      container_name: plex
      network_mode: host
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - VERSION=docker
      volumes:
        - ${CONFIG_BASE_PATH}/plex:/config
        - ${DATA_BASE_PATH}/media/tv:/tv
        - ${DATA_BASE_PATH}/media/movies:/movies
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/sonarr:/config
        - ${DATA_BASE_PATH}:/data
      ports:
        - 8989:8989
    radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/radarr:/config
        - ${DATA_BASE_PATH}:/data
      ports:
        - 7878:7878
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/jackett:/config
        - ${DATA_BASE_PATH}/transmission/watch:/downloads
      ports:
        - 9117:9117
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/ombi:/config
      ports:
        - 3579:3579
    lazylibrarian:
      image: linuxserver/lazylibrarian
      container_name: lazylibrarian
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
        - DOCKER_MODS=linuxserver/calibre-web:calibre
      volumes:
        - ${CONFIG_BASE_PATH}/lazylibrarian:/config
        - ${DATA_BASE_PATH}/transmission/downloads/complete:/downloads
        - ${DATA_BASE_PATH}/media/books:/books
      ports:
        - 5299:5299
    calibre-web:
      image: linuxserver/calibre-web
      container_name: calibre-web
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${CONFIG_BASE_PATH}/calibre-web:/config
        - ${DATA_BASE_PATH}/transmission/downloads:/downloads
        - ${DATA_BASE_PATH}/media/books:/books
      ports:
        - 8083:8083

