version: '3'
services:
  vpn:
    image: lscr.io/linuxserver/wireguard:alpine
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/wireguard:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/transmission:/config
      - ${DATA_BASE_PATH}/transmission/downloads:/downloads
      - ${DATA_BASE_PATH}/transmission/watch:/watch
    network_mode: "service:vpn"
  nginx:
    image: nginx:1.23-alpine
    container_name: transmission-proxy
    ports:
      - "9091:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
    volumes:
      - ${CONFIG_BASE_PATH}/plex:/config
      - ${DATA_BASE_PATH}/media/tv:/tv
      - ${DATA_BASE_PATH}/media/movies:/movies
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/sonarr:/config
      - ${DATA_BASE_PATH}:/data
    ports:
      - 8989:8989
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/radarr:/config
      - ${DATA_BASE_PATH}:/data
    ports:
      - 7878:7878
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/jackett:/config
      - ${DATA_BASE_PATH}/transmission/watch:/downloads
    ports:
      - 9117:9117
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/ombi:/config
    ports:
      - 3579:3579
  lazylibrarian:
    image: linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - DOCKER_MODS=linuxserver/calibre-web:calibre
    volumes:
      - ${CONFIG_BASE_PATH}/lazylibrarian:/config
      - ${DATA_BASE_PATH}/transmission/downloads/complete:/downloads
      - ${DATA_BASE_PATH}/media/books:/books
    ports:
      - 5299:5299
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/calibre-web:/config
      - ${DATA_BASE_PATH}/transmission/downloads:/downloads
      - ${DATA_BASE_PATH}/media/books:/books
    ports:
      - 8083:8083
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - ${CONFIG_BASE_PATH}/organizr:/config
    ports:
      - 9000:80
