version: '3'
services:
    nordvpn:
      image: bubuntux/nordvpn
      cap_add:
        - NET_ADMIN
        - SYS_MODULE
      devices:
        - /dev/net/tun
      environment:
        - USER=${VPN_USER}
        - PASS=${VPN_PASS}
        - CONNECT=P2P
        - TECHNOLOGY=OpenVPN
    transmission:
      image: linuxserver/transmission
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/transmission/config:/config
        - ${SERVER_BASE_PATH}/transmission/downloads:/downloads
        - ${SERVER_BASE_PATH}/transmission/watch:/watch
      network_mode: "service:nordvpn"
    nginx:
      image: nginx:1.13-alpine
      stdin_open: true
      ports:
        - "9091:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - nordvpn:transmission
    plex:
      image: linuxserver/plex
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - VERSION=docker
        #- ADVERTISE_IP=192.168.7.39:32400
      volumes:
        - ${SERVER_BASE_PATH}/plex/config:/config
        - ${SERVER_BASE_PATH}/plex/media/shows:/tvseries
        - ${SERVER_BASE_PATH}/plex/media/movies:/movies
     # ports:
     #   - 32400:32400
      network_mode: host
    sonarr:
      image: linuxserver/sonarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/sonarr/config:/config
        - ${SERVER_BASE_PATH}/plex/media/shows:/tv
        - ${SERVER_BASE_PATH}/transmission/downloads:/downloads
      ports:
        - 8989:8989
    radarr:
      image: linuxserver/radarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/radarr/config:/config
        - ${SERVER_BASE_PATH}/plex/media/movies:/movies
        - ${SERVER_BASE_PATH}/transmission/downloads:/downloads
      ports:
        - 7878:7878
    jackett:
      image: linuxserver/jackett
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/jackett/config:/config
        - ${SERVER_BASE_PATH}/transmission/watch:/downloads
      ports:
        - 9117:9117
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/ombi/config:/config
      ports:
        - 3579:3579
