version: '3'
services:
    nordvpn:
      image: bubuntux/nordvpn:v3.9.1
      cap_add:
        - NET_ADMIN
#        - SYS_MODULE
#      sysctls:
#        - net.ipv4.conf.all.rp_filter=2
      devices:
        - /dev/net/tun
      environment:
        - USER=${VPN_USER}
        - PASS=${VPN_PASS}
        - CONNECT=us -g p2p
        - TECHNOLOGY=NordLynx
    transmission:
      image: linuxserver/transmission
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/transmission/config:/config
        - ${TRANS_DL}:/downloads
        - ${SERVER_BASE_PATH}/transmission/watch:/watch
      network_mode: "service:nordvpn"
    nginx:
      image: nginx:1.13-alpine
      stdin_open: true
      ports:
        - "9091:80"
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      links:
        - nordvpn:transmission
    plex:
      image: linuxserver/plex
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - VERSION=docker
        #- ADVERTISE_IP=192.168.7.39:32400
      volumes:
        - ${SERVER_BASE_PATH}/plex/config:/config
        - ${SERVER_BASE_PATH}/plex/media/shows:/tvseries
        - ${SERVER_BASE_PATH}/plex/media/movies:/movies
     # ports:
     #   - 32400:32400
      network_mode: host
    sonarr:
      image: linuxserver/sonarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/sonarr/config:/config
        - ${SERVER_BASE_PATH}/plex/media/shows:/tv
        - ${TRANS_DL}:/downloads
      ports:
        - 8989:8989
    radarr:
      image: linuxserver/radarr
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/radarr/config:/config
        - ${SERVER_BASE_PATH}/plex/media/movies:/movies
        - ${TRANS_DL}:/downloads
      ports:
        - 7878:7878
    jackett:
      image: linuxserver/jackett
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/jackett/config:/config
        - ${SERVER_BASE_PATH}/transmission/watch:/downloads
      ports:
        - 9117:9117
    ombi:
      image: linuxserver/ombi
      container_name: ombi
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/ombi/config:/config
      ports:
        - 3579:3579
    lazylibrarian:
      image: linuxserver/lazylibrarian
      container_name: lazylibrarian
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
        - DOCKER_MODS=linuxserver/calibre-web:calibre
      volumes:
        - ${SERVER_BASE_PATH}/lazylibrarian/config:/config
        - ${TRANS_DL}/complete:/downloads
        - ${SERVER_BASE_PATH}/calibre/library:/books
      ports:
        - 5299:5299
    calibre-web:
      image: linuxserver/calibre-web
      container_name: calibre-web
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TIMEZONE}
      volumes:
        - ${SERVER_BASE_PATH}/calibre-web/config:/config
        - ${TRANS_DL}:/downloads
        - ${SERVER_BASE_PATH}/calibre/library:/books
      ports:
        - 8083:8083

